<?php

namespace ContainerAiU42X9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I60bMqkService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.i60bMqk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i60bMqk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.i60bMqk.App\\Entity\\Categories', NULL, 'Cannot autowire service ".service_locator.i60bMqk": it needs an instance of "App\\Entity\\Categories" but this type has been excluded in "config/services.yaml".'],
        ], [
            'category' => 'App\\Entity\\Categories',
        ]);
    }
}
