<?php

namespace ContainerAiU42X9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaires2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.kxstp_I.App\Entity\Commentaires' shared service.
     *
     * @return \App\Entity\Commentaires
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kxstp_I": it needs an instance of "App\\Entity\\Commentaires" but this type has been excluded in "config/services.yaml".');
    }
}
