<?php

namespace ContainerAiU42X9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CategoriesType' shared autowired service.
     *
     * @return \App\Form\CategoriesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CategoriesType'] = new \App\Form\CategoriesType();
    }
}
