<?php

namespace ContainerAiU42X9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\FileUploaderService' shared autowired service.
     *
     * @return \App\Service\FileUploaderService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\FileUploaderService'] = new \App\Service\FileUploaderService((\dirname(__DIR__, 4).'/public/uploads'), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')));
    }
}
