<?php

namespace ContainerAiU42X9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamAuthentificatorAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\TeamAuthentificatorAuthenticator' shared autowired service.
     *
     * @return \App\Security\TeamAuthentificatorAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\TeamAuthentificatorAuthenticator'] = new \App\Security\TeamAuthentificatorAuthenticator(($container->services['router'] ?? self::getRouterService($container)));
    }
}
