<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZWW3LcW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZWW3LcW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZWW3LcW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZWW3LcW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZWW3LcW\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZWW3LcW',
    'container.build_id' => '1eb4a7f8',
    'container.build_time' => 1690884252,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZWW3LcW');
