<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEugKChu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEugKChu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEugKChu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEugKChu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEugKChu\App_KernelDevDebugContainer([
    'container.build_hash' => 'EugKChu',
    'container.build_id' => '54e0a1fb',
    'container.build_time' => 1690982401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEugKChu');
