<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKIxZ1gs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKIxZ1gs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKIxZ1gs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKIxZ1gs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKIxZ1gs\App_KernelDevDebugContainer([
    'container.build_hash' => 'KIxZ1gs',
    'container.build_id' => '3e014d67',
    'container.build_time' => 1690962326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKIxZ1gs');
