<?php

namespace ContainerSuRXVjx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8IzX0f9.App\Entity\Categories' shared service.
     *
     * @return \App\Entity\Categories
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8IzX0f9": it needs an instance of "App\\Entity\\Categories" but this type has been excluded in "config/services.yaml".');
    }
}
