<?php

namespace ContainerSuRXVjx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentairesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HBWOX4X.App\Entity\Commentaires' shared service.
     *
     * @return \App\Entity\Commentaires
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HBWOX4X": it needs an instance of "App\\Entity\\Commentaires" but this type has been excluded in "config/services.yaml".');
    }
}
